//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaseSlovoApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilten> Bilteni { get; set; }
        public virtual DbSet<Knjiga> Knjige { get; set; }
        public virtual DbSet<Komentar> Komentari { get; set; }
        public virtual DbSet<Korisnik> Korisnici { get; set; }
        public virtual DbSet<OcjenaKnjige> OcjeneKnjiga { get; set; }
        public virtual DbSet<OcjenaTeksta> OcjeneTekstova { get; set; }
        public virtual DbSet<Tekst> Tekstovi { get; set; }
        public virtual DbSet<Tema> Teme { get; set; }
        public virtual DbSet<Vrsta> Vrste { get; set; }
        public virtual DbSet<Clanstvo> Clanstva { get; set; }
    }
}
