//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaseSlovoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knjiga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Knjiga()
        {
            this.OcjeneKnjiga = new HashSet<OcjenaKnjige>();
        }
    
        public int KnjigaID { get; set; }
        public string Autori { get; set; }
        public string Naslov { get; set; }
        public string Signatura { get; set; }
        public string Izdavac { get; set; }
        public short Godina { get; set; }
        public int VrstaID { get; set; }
        public double SrednjaOcjena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcjenaKnjige> OcjeneKnjiga { get; set; }
        public virtual Vrsta Vrsta { get; set; }
    }
}
