//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaseSlovoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tekst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tekst()
        {
            this.Komentari = new HashSet<Komentar>();
            this.OcjeneTekstova = new HashSet<OcjenaTeksta>();
        }
    
        public int TekstID { get; set; }
        public string Sadrzaj { get; set; }
        public string Naslov { get; set; }
        public int AutorID { get; set; }
        public int TemaID { get; set; }
        public int VrstaID { get; set; }
        public System.DateTime DatumVrijeme { get; set; }
        public double SrednjaOcjena { get; set; }
        public Nullable<int> BiltenID { get; set; }
        public bool Privatan { get; set; }
        public bool Objavljen { get; set; }
        public string LektorovKomentar { get; set; }
        public bool Odabran { get; set; }
    
        public virtual Bilten Bilten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komentar> Komentari { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcjenaTeksta> OcjeneTekstova { get; set; }
        public virtual Tema Tema { get; set; }
        public virtual Vrsta Vrsta { get; set; }
    }
}
